export const BANKS = [
  "Adam & Company",
  "AIB Group (UK) plc",
  "Aldermore Bank",
  "Allied Irish Bank (GB)",
  "Atom Bank",
  "Banco Santander",
  "Bank of China (UK)",
  "Bank of Ireland UK",
  "Bank of Scotland",
  "Barclays Bank",
  "Cambridge & Counties Bank",
  "Charity Bank",
  "Chase UK",
  "Close Brothers",
  "Clydesdale Bank",
  "Co-operative Bank",
  "Coutts & Co",
  "Coventry Building Society",
  "Cynergy Bank",
  "Danske Bank UK",
  "First Direct",
  "First Trust Bank",
  "Gatehouse Bank",
  "Halifax",
  "Hampden & Co",
  "Handelsbanken UK",
  "HSBC UK",
  "ICICI Bank UK",
  "Investec Bank UK",
  "JP Morgan Europe",
  "Kleinwort Hambros",
  "Lloyds Bank",
  "Metro Bank",
  "Monzo Bank",
  "Nationwide Building Society",
  "NatWest",
  "OakNorth Bank",
  "Paragon Bank",
  "Reliance Bank",
  "Revolut Ltd",
  "Royal Bank of Scotland",
  "Sainsbury's Bank",
  "Shawbrook Bank",
  "Skipton Building Society",
  "Starling Bank",
  "Tesco Bank",
  "The Access Bank UK",
  "The Bank of London",
  "The Co-operative Bank",
  "Triodos Bank UK",
  "TSB Bank",
  "UBS UK",
  "Ulster Bank UK",
  "Virgin Money UK",
  "Yorkshire Bank",
  "Zopa Bank",
];
